#!/bin/sh

# ENV

export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=river
export WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-1}
export XDG_RUNTIME_DIR=/run/user/$(id -u)
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"

systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd --all
systemctl --user restart xdg-desktop-portal
systemctl --user restart mpd-mpris

#-----------------------------
#----------AUTOSTART----------
#-----------------------------
kanshi &
waybar &
swww-daemon &
dunst &

#-----------------------------
#----KEYBOARD & MOUSE/PAD-----
#-----------------------------

riverctl keyboard-layout us
riverctl map normal Super E spawn "riverctl keyboard-layout us"
riverctl map normal Super S spawn "riverctl keyboard-layout es"

for pad in $(riverctl list-inputs | grep -i "touchpad"); do
  riverctl input $pad events enabled
  riverctl input $pad pointer-accel 0.8
  riverctl input $pad tap enabled
done

riverctl set-cursor-warp on-focus-change

#-----------------------------
#----------SHORTCUTS----------
#-----------------------------

riverctl map normal Super M  spawn "sh ~/Scripts/toggler.sh"
riverctl map normal Super Q spawn kitty
riverctl map normal Super C close
riverctl map normal Super+Shift E exit
riverctl map normal Super Z spawn "wofi --show drun"
riverctl map normal Super A spawn "sh ~/Scripts/restart.sh"
riverctl map normal Super W spawn "sh ~/Scripts/wallswitch.sh"
riverctl map normal Super D spawn "kitty yazi"
# Full screen of focused monitor to file

# Full screen of monitor under cursor to file
riverctl map normal Super Print spawn "grim -o \$(slurp -p -f '%o') ~/Media/Pictures/Screenshots/\$(date +'%Y-%m-%d-%H%M%S').png"

# Full screen of monitor under cursor to clipboard
riverctl map normal Super+Shift Print spawn "grim -o \$(slurp -p -f '%o') - | wl-copy"

# Selected area to clipboard - Escaped so slurp doesn't run on init
riverctl map normal Super+Control Print spawn "grim -g \"\$(slurp)\" - | wl-copy"

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map normal Super V toggle-float

for i in $(seq 1 9); do
  tags=$((1 << ($i - 1)))

  # Super+[1-9] to focus tag [0-8]
  riverctl map normal Super $i set-focused-tags $tags

  # Super+Shift+[1-9] to tag focused view with tag [0-8]
  riverctl map normal Super+Shift $i set-view-tags $tags

  # Super+Control+[1-9] to toggle focus of tag [0-8]
  riverctl map normal Super+Control $i toggle-focused-tags $tags

  # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
  riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
# Eject the optical drive (well if you still have one that is)
riverctl map normal XF86Eject spawn 'eject -T'

# Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)

riverctl map normal Super F4 spawn 'sh ~/Scripts/lock.sh'

# Output
riverctl map normal Super F1 spawn 'pamixer --toggle-mute'
riverctl map normal Super F2 spawn 'pamixer -d 5'
riverctl map normal Super F3 spawn 'pamixer -i 5'

# Input 

riverctl map normal Super F7 spawn 'pamixer --default-source --toggle-mute'
riverctl map normal Super F8 spawn 'pamixer --default-source -d 5'
riverctl map normal Super F9 spawn 'pamixer --default-source -i 5'

# Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
riverctl map normal Super F10 spawn 'playerctl play-pause'
riverctl map normal Super F11 spawn 'playerctl previous'
riverctl map normal Super F12 spawn 'playerctl next'

# Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
riverctl map normal Super F5 spawn 'brightnessctl set 5%-'
riverctl map normal Super F6 spawn 'brightnessctl set +5%'

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0xa9b665 
riverctl border-color-unfocused 0xa96b3e
# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &


