music_directory "~/Media/Music/"
db_file "~/.config/mpd/tag_cache"
log_file "~/.config/mpd/mpd.log"
pid_file "~/.config/mpd/pid"
state_file "~/.config/mpd/state"
restore_paused "yes"

auto_update "yes"
follow_outside_symlinks "no"
follow_inside_symlinks "no"

audio_output {
    type        "pipewire"
    name        "MPD Output"
    mixer_type  "software"
}

audio_output {
   type   "fifo"
   name   "my_fifo"
   path   "/tmp/mpd.fifo"
   format "44100:16:2"
}

bind_to_address "127.0.0.1"
port "6600"
